# Generated by Django 3.2.9 on 2022-11-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('year', models.CharField(max_length=100, unique=True)),
                ('userRating', models.FloatField()),
                ('link', models.CharField(max_length=100)),
                ('poster_path', models.CharField(max_length=200)),
                ('popularity', models.FloatField()),
            ],
        ),
    ]
