# Generated by Django 3.2.9 on 2022-11-21 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_scoreboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
